modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="patchouliquests"
version="${file.jarVersion}"
displayName="Patchouli Quests"
authors="jihuayu"
description="Patchouli Quests"
[[dependencies.patchouliquests]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.15.2-1.2,)"
    ordering="BEFORE"
    side="BOTH"