modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="patchouliquests"
version="${file.jarVersion}"
displayName="Patchouli Quests"
authors="jihuayu"
description="Patchouli Quests"
[[dependencies.cuisine]]
    modId="patchouli"
    mandatory=true
    ordering="BEFORE"
    side="BOTH"